export const studentFormOct18 = [
  {
    name: 'Section Header',
    type: 'sectionHeader',
    inputLabel: 'Personal Details',
    keyName: 'personalDetails',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'First Name',
    keyName: 'firstName',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
      {
        settingType: 'onlyLetters',
        value: true,
        name: 'Only Letters',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'Middle Name',
    keyName: 'middleName',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: false,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
      {
        settingType: 'onlyLetters',
        value: true,
        name: 'Only Letters',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'Last Name',
    keyName: 'lastName',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: false,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
      {
        settingType: 'onlyLetters',
        value: true,
        name: 'Only Letters',
      },
    ],
  },
  {
    name: 'Email',
    type: 'email',
    inputLabel: 'Email Id',
    keyName: 'email',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'EmailIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'exceptDomains',
        value: [],
        name: 'Except Domains(comma seperated)',
      },
      {
        settingType: 'onlyDomains',
        value: [],
        name: 'Only Domains(comma seperated)',
      },
    ],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'Contact Number',
    keyName: 'contactNumber',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: true,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: false,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: null,
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: '100000000000000000',
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: '10',
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: '10',
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'Identification Mark / Birth Mark',
    keyName: 'identificationMark',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Gender',
    keyName: 'gender',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'male,female,other',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Mother Tongue',
    keyName: 'motherTongue',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'kannada,kodava,tulu,hindi,tamil,telugu,malyalam,punjabi,urdu,other',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'Place of Birth',
    keyName: 'placeOfBirth',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
      {
        settingType: 'onlyLetters',
        value: true,
        name: 'Only Letters',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Blood Group',
    keyName: 'bloodGroup',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'A+, A-, B+, B-, AB+, AB-, O+, O-',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'Aadhar Number',
    keyName: 'aadharNumber',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: true,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: true,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: null,
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: '100000000000000000000',
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: '12',
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: '12',
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'PAN Number',
    keyName: 'panNumber',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: '10',
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: '10',
        name: 'Max Length',
      },
      {
        settingType: 'onlyLetters',
        value: false,
        name: 'Only Letters',
      },
    ],
  },
  {
    name: 'Section Header',
    type: 'sectionHeader',
    inputLabel: 'Parent Details',
    keyName: 'personalDetails',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'Father Full Name',
    keyName: 'fatherFullName',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
      {
        settingType: 'onlyLetters',
        value: true,
        name: 'Only Letters',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'Mother Name',
    keyName: 'motherName',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
      {
        settingType: 'onlyLetters',
        value: true,
        name: 'Only Letters',
      },
    ],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'Parent Contact Number',
    keyName: 'parentContactNumber',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: true,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: false,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: null,
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: '100000000000000000',
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: '10',
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: '12',
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Email',
    type: 'email',
    inputLabel: 'Parent Email ID',
    keyName: 'parentEmail',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'EmailIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'exceptDomains',
        value: [],
        name: 'Except Domains(comma seperated)',
      },
      {
        settingType: 'onlyDomains',
        value: [],
        name: 'Only Domains(comma seperated)',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'Gaurdian Name',
    keyName: 'gaurdianName',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
      {
        settingType: 'onlyLetters',
        value: true,
        name: 'Only Letters',
      },
    ],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'Gaurdian Contact Number',
    keyName: 'gaurdianContactNumber',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: true,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: false,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: null,
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: '100000000000000000',
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: '10',
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: '10',
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Section Header',
    type: 'sectionHeader',
    inputLabel: 'Admission Details',
    keyName: 'personalDetails',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Religion',
    keyName: 'religion',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'hindu,muslim,christian,sikh,other',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'Caste',
    keyName: 'caste',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
      {
        settingType: 'onlyLetters',
        value: true,
        name: 'Only Letters',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'USN Number',
    keyName: 'usnNumber',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: false,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: '10',
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: '10',
        name: 'Max Length',
      },
    ],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'Admission Number',
    keyName: 'admissionNumber',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: true,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: null,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: null,
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: '100000000000000000000',
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: '',
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: '10',
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Category',
    keyName: 'category',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: '1a,1b,2a,2b,3a,3b,SC,ST,OBC,EWAS',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Plain Text',
    type: 'plainText',
    inputLabel: 'Nationality',
    keyName: 'nationality',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'minLength',
        value: null,
        name: 'Min Length',
      },
      {
        settingType: 'maxLength',
        value: 1000,
        name: 'Max Length',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Rural / Urban Status',
    keyName: 'ruralUrbanStatus',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'Rural,Urban',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Year of Admission',
    keyName: 'yearOfAdmission',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: '2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Seat Type',
    keyName: 'seatType',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'CET-regular,CET-SNQ,Management-Karnataka,Management-Non-Karnataka',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Admission Status',
    keyName: 'admissionStatus',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'pending,completed',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Admission Type',
    keyName: 'admissionType',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'regular,lateral-Entry,change-of-College',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'Discount / Scholorship',
    keyName: 'discountOrScholorship',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: false,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: false,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: null,
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: 10000000000,
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: null,
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: 100,
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'Annual Income',
    keyName: 'annualIncome',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: true,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: false,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: '10000',
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: '100000000000000',
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: null,
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: 100,
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Section Header',
    type: 'sectionHeader',
    inputLabel: '',
    keyName: 'personalDetails',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'Entrance Test Marks',
    keyName: 'entranceTestMarks',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: false,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: false,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: null,
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: 10000000000,
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: null,
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: 100,
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Department',
    keyName: 'department',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: [],
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: true,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Admission Semester',
    keyName: 'admissionSemester',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: '1st-Semester,3rd-Semester',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: true,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: '1',
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Checkbox',
    type: 'checkbox',
    inputLabel: 'Physically Disabled',
    keyName: 'physicallyChallenged',
    value: false,
    initialValue: false,
    errorMessage: '',
    icon: 'CheckboxIconComponent',
    settings: [
      {
        settingType: 'defaultChecked',
        value: false,
        name: 'Default Checked',
      },
      {
        settingType: 'expectedTrue',
        value: false,
        name: 'Expected True',
      },
      {
        settingType: 'expectedFalse',
        value: false,
        name: 'Expected False',
      },
    ],
  },
  {
    name: 'Checkbox',
    type: 'checkbox',
    inputLabel: 'Kannada Medium',
    keyName: 'kannadaMedium',
    value: false,
    initialValue: false,
    errorMessage: '',
    icon: 'CheckboxIconComponent',
    settings: [
      {
        settingType: 'defaultChecked',
        value: false,
        name: 'Default Checked',
      },
      {
        settingType: 'expectedTrue',
        value: false,
        name: 'Expected True',
      },
      {
        settingType: 'expectedFalse',
        value: false,
        name: 'Expected False',
      },
    ],
  },
  {
    name: 'Checkbox',
    type: 'checkbox',
    inputLabel: 'Hyderabad Karnataka',
    keyName: 'hyderabadKarnataka',
    value: false,
    initialValue: false,
    errorMessage: '',
    icon: 'CheckboxIconComponent',
    settings: [
      {
        settingType: 'defaultChecked',
        value: false,
        name: 'Default Checked',
      },
      {
        settingType: 'expectedTrue',
        value: false,
        name: 'Expected True',
      },
      {
        settingType: 'expectedFalse',
        value: false,
        name: 'Expected False',
      },
    ],
  },
  {
    name: 'Checkbox',
    type: 'checkbox',
    inputLabel: 'App Downloaded',
    keyName: 'appDownloaded',
    value: false,
    initialValue: false,
    errorMessage: '',
    icon: 'CheckboxIconComponent',
    settings: [
      {
        settingType: 'defaultChecked',
        value: false,
        name: 'Default Checked',
      },
      {
        settingType: 'expectedTrue',
        value: false,
        name: 'Expected True',
      },
      {
        settingType: 'expectedFalse',
        value: false,
        name: 'Expected False',
      },
    ],
  },
  {
    name: 'Section Header',
    type: 'sectionHeader',
    inputLabel: '',
    keyName: 'addSectionname',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [],
  },
  {
    name: 'Checkbox',
    type: 'checkbox',
    inputLabel: 'Access for Website',
    keyName: 'accessforWebsite',
    value: false,
    initialValue: false,
    errorMessage: '',
    icon: 'CheckboxIconComponent',
    settings: [
      {
        settingType: 'defaultChecked',
        value: false,
        name: 'Default Checked',
      },
      {
        settingType: 'expectedTrue',
        value: false,
        name: 'Expected True',
      },
      {
        settingType: 'expectedFalse',
        value: false,
        name: 'Expected False',
      },
    ],
  },
  {
    name: 'Checkbox',
    type: 'checkbox',
    inputLabel: 'Fees Paid',
    keyName: 'feesPaid',
    value: false,
    initialValue: false,
    errorMessage: '',
    icon: 'CheckboxIconComponent',
    settings: [
      {
        settingType: 'defaultChecked',
        value: false,
        name: 'Default Checked',
      },
      {
        settingType: 'expectedTrue',
        value: false,
        name: 'Expected True',
      },
      {
        settingType: 'expectedFalse',
        value: false,
        name: 'Expected False',
      },
    ],
  },
  {
    name: 'Checkbox',
    type: 'checkbox',
    inputLabel: 'Hostel Required',
    keyName: 'hostelRequired',
    value: false,
    initialValue: false,
    errorMessage: '',
    icon: 'CheckboxIconComponent',
    settings: [
      {
        settingType: 'defaultChecked',
        value: false,
        name: 'Default Checked',
      },
      {
        settingType: 'expectedTrue',
        value: false,
        name: 'Expected True',
      },
      {
        settingType: 'expectedFalse',
        value: false,
        name: 'Expected False',
      },
    ],
  },
  {
    name: 'Checkbox',
    type: 'checkbox',
    inputLabel: 'Transport Required',
    keyName: 'transportRequired',
    value: false,
    initialValue: false,
    errorMessage: '',
    icon: 'CheckboxIconComponent',
    settings: [
      {
        settingType: 'defaultChecked',
        value: false,
        name: 'Default Checked',
      },
      {
        settingType: 'expectedTrue',
        value: false,
        name: 'Expected True',
      },
      {
        settingType: 'expectedFalse',
        value: false,
        name: 'Expected False',
      },
    ],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'CET Ranking',
    keyName: 'cetRanking',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: false,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: false,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: '0',
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: '1000000000000',
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: null,
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: 100,
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Fees Structure',
    keyName: 'feeStructure',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'CET-free,CET-Payment,Management',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Date',
    type: 'date',
    inputLabel: 'Date of Join / Admission',
    keyName: 'dateOfJoin',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'CalendarIconComponent',
    settings: [
      {
        settingType: 'required',
        value: true,
        name: 'Required',
      },
      {
        settingType: 'minDate',
        value: '2024-08-26',
        name: 'Min Date',
      },
      {
        settingType: 'maxDate',
        value: '2032-01-01',
        name: 'Max Date',
      },
    ],
  },
  {
    name: 'Single Select',
    type: 'singleSelect',
    inputLabel: 'Previous Education',
    keyName: 'previousEducation',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'SelectIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Non Empty',
      },
      {
        settingType: 'options',
        value: 'PUC/12th,Diploma',
        name: 'Options(comma seperated)',
      },
      {
        settingType: 'enableDynamincOption',
        value: false,
        name: 'Enable Dynaminc Option',
      },
      {
        settingType: 'dynamincOptionIndex',
        value: 0,
        name: 'Dynaminc Option index',
      },
    ],
  },
  {
    name: 'Number',
    type: 'number',
    inputLabel: 'Diploma Marks',
    keyName: 'diplomaMarks',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'NumberIconComponent',
    settings: [
      {
        settingType: 'nonZero',
        value: false,
        name: 'Non Zero',
      },
      {
        settingType: 'noDecimals',
        value: true,
        name: 'No Decimals',
      },
      {
        settingType: 'min',
        value: null,
        name: 'Minimum',
      },
      {
        settingType: 'max',
        value: 10000000000,
        name: 'Maximum',
      },
      {
        settingType: 'minDigits',
        value: null,
        name: 'Minimum Digits',
      },
      {
        settingType: 'maxDigits',
        value: 100,
        name: 'Maximum Digits',
      },
    ],
  },
  {
    name: 'Section Header',
    type: 'sectionHeader',
    inputLabel: '',
    keyName: 'formGroups',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [],
  },
  {
    name: 'Nested Form',
    type: 'nestedForm',
    inputLabel: 'PU / 12th Marks',
    keyName: 'puOr12thMarks',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: false,
        name: 'Required',
      },
    ],
    hide: false,
  },
  {
    name: 'Nested Form',
    type: 'nestedForm',
    inputLabel: 'Student Documents Form',
    keyName: 'documents',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: false,
        name: 'Required',
      },
    ],
    hide: false,
  },
  {
    name: 'Nested Form',
    type: 'nestedForm',
    inputLabel: 'Bank Details Form',
    keyName: 'bankDetails',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: false,
        name: 'Required',
      },
    ],
    hide: false,
  },
  {
    name: 'Nested Form',
    type: 'nestedForm',
    inputLabel: 'Present Address Form',
    keyName: 'presentAddress',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: true,
        name: 'Required',
      },
    ],
    hide: false,
  },
  {
    name: 'Checkbox',
    type: 'checkbox',
    inputLabel: 'Permanent Address is same as Present Address',
    keyName: 'permanentSameAsPresent',
    value: false,
    initialValue: false,
    errorMessage: '',
    icon: 'CheckboxIconComponent',
    settings: [
      {
        settingType: 'defaultChecked',
        value: false,
        name: 'Default Checked',
      },
      {
        settingType: 'expectedTrue',
        value: false,
        name: 'Expected True',
      },
      {
        settingType: 'expectedFalse',
        value: false,
        name: 'Expected False',
      },
    ],
  },
  {
    name: 'Nested Form',
    type: 'nestedForm',
    inputLabel: 'Permanent Address Form',
    keyName: 'permanentAddress',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'PlainTextIconComponent',
    settings: [
      {
        settingType: 'nonEmpty',
        value: false,
        name: 'Required',
      },
    ],
    hide: false,
  },
  {
    name: 'File',
    type: 'file',
    inputLabel: 'Profile Photo',
    keyName: 'profilePhoto',
    value: '',
    initialValue: '',
    errorMessage: '',
    icon: 'FileIconComponent',
    settings: [
      {
        settingType: 'required',
        value: true,
        name: 'Required',
      },
      {
        settingType: 'accept',
        value: 'image/png,image/jpeg',
        name: 'Accept',
      },
    ],
  },
];
